export const ranks = [
  {
    id: "aspiring",
    label: "Aspiring",
    accent: "bg-rank-aspiring",
    description: "Registrieren reicht – E-Mail bestätigen und loslegen.",
    access: "Community lesen, Events sehen",
  },
  {
    id: "starter",
    label: "Starter",
    accent: "bg-rank-starter",
    description: "Aktives Gewerbe – eine Gewerbeanmeldung hochladen.",
    access: "Schreiben, Branchen-Channels, kostenlose Events",
  },
  {
    id: "builder",
    label: "Builder",
    accent: "bg-rank-builder",
    description: "50k–250k EUR Umsatz/Jahr – ein Umsatznachweis.",
    access: "Mentoren, bezahlte Events, als Mentor (max. 50€/Monat)",
  },
  {
    id: "scaler",
    label: "Scaler",
    accent: "bg-rank-scaler",
    description: "250k–1M EUR Umsatz/Jahr – BWA oder Steuerbescheid.",
    access: "Premium Channels, Deal-Board, Mentor max. 150€/Monat",
  },
  {
    id: "elite",
    label: "Elite",
    accent: "bg-rank-elite",
    description: "Über 1M EUR Umsatz/Jahr – Jahresabschluss oder BWA.",
    access: "VIP Events, Mastermind, Mentor max. 500€/Monat",
  },
];

export const founderPro = {
  name: "Founder Pro",
  price: "14,99 EUR",
  interval: "Monat",
  benefits: [
    "Zugang zu Premium-Channels",
    "Exklusive Ressourcen und Partner-Deals",
    "Früher Zugang zu limitierten Events",
  ],
};

export const monetizationPillars = [
  {
    title: "Events",
    description: "Kostenlose Community-Calls plus bezahlte Workshops, Networking-Dinner und Konferenzen.",
    revenue: "Ticketverkäufe",
  },
  {
    title: "Mentoren",
    description: "Verifizierte Scaler+ Mentoren bieten 1:1 Sessions, Pakete und SOS-Calls an.",
    revenue: "15% Plattform-Provision",
  },
  {
    title: "Founder Pro",
    description: "Optionales Upgrade für Power-User, ohne Rang oder Community-Zugang zu verkaufen.",
    revenue: "14,99 EUR monatlich",
  },
];

export const mentorsPreview = [
  {
    name: "Sarah Keller",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80",
    company: "DTC Growth Studio",
    expertise: "E-Commerce Skalierung",
    rank: "scaler",
    price: "149 EUR / Session",
  },
  {
    name: "Murat Aydin",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80",
    company: "Creator Commerce Lab",
    expertise: "TikTok Ads & Creator Funnels",
    rank: "builder",
    price: "99 EUR / Session",
  },
  {
    name: "Jonas Weber",
    avatar_url: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&q=80",
    company: "Ops & Finance Advisory",
    expertise: "Finanzen, BWA und Prozesse",
    rank: "elite",
    price: "249 EUR / Session",
  },
];

export const dashboardSteps = [
  {
    id: "profile",
    title: "Profil vervollständigen",
    description: "Name, Unternehmen, Branche und Social Links eintragen.",
  },
  {
    id: "verify",
    title: "Rang verifizieren",
    description: "Dokument hochladen, damit Admins deinen Unternehmer-Rang bestätigen.",
  },
  {
    id: "community",
    title: "Community beitreten",
    description: "Entdecke Branchen-Channels und tritt deiner ersten Gruppe bei.",
  },
];

export const rankOrder = {
  aspiring: 0,
  starter: 1,
  builder: 2,
  scaler: 3,
  elite: 4,
};

export function canAccessRank(userRank = "aspiring", minRank = "aspiring") {
  return (rankOrder[userRank] ?? 0) >= (rankOrder[minRank] ?? 0);
}

export function canAccessChannel(userRank = "aspiring", minRank = "aspiring", isPro = false, requiresPro = false) {
  return canAccessRank(userRank, minRank) && (!requiresPro || isPro);
}

export function getRankLabel(rank = "aspiring") {
  return ranks.find((item) => item.id === rank)?.label ?? "Aspiring";
}

export const communityChannels = [
  {
    slug: "reselling",
    name: "Reselling",
    category: "Reselling",
    description:
      "High-End Streetwear, Sneakers, Hardware & Collectibles: Sourcing, Authentifizierung, Margen und Verkaufsstrategien.",
    min_rank: "aspiring",
    icon: "R",
    member_count: 47,
  },
  {
    slug: "dropshipping",
    name: "Dropshipping",
    category: "Dropshipping",
    description: "Shop-Aufbau, Lieferanten, Creatives und Testing für Dropshipping.",
    min_rank: "aspiring",
    icon: "D",
    member_count: 41,
  },
  {
    slug: "e-commerce",
    name: "E-Commerce",
    category: "E-Commerce",
    description: "DTC, Shops, Conversion, Logistik und Wachstum für Online-Händler.",
    min_rank: "aspiring",
    icon: "E",
    member_count: 50,
  },
  {
    slug: "amazon-fba",
    name: "Amazon FBA",
    category: "Amazon FBA",
    description: "Private Label, Produktrecherche, Launch, Listing-Optimierung und Amazon Operations.",
    min_rank: "aspiring",
    icon: "A",
    member_count: 35,
  },
  {
    slug: "tiktok-creator",
    name: "TikTok Creator",
    category: "TikTok Creator",
    description: "Content, Creator Funnels, Live Shopping und Social Commerce.",
    min_rank: "aspiring",
    icon: "T",
    member_count: 49,
  },
  {
    slug: "tiktok-shop",
    name: "TikTok Shop",
    category: "TikTok Shop",
    description: "Shop-Setup, Creator-Affiliates, GMV-Wachstum, Live Shopping und Kurzvideo-Commerce.",
    min_rank: "aspiring",
    icon: "TS",
    member_count: 44,
  },
  {
    slug: "ki-creator",
    name: "KI Creator",
    category: "KI Creator",
    description: "KI-Workflows, Content-Produktion, Automationen und Creator-Tools.",
    min_rank: "aspiring",
    icon: "KI",
    member_count: 38,
  },
  {
    slug: "trading",
    name: "Trading",
    category: "Trading",
    description: "Austausch zu Trading-Strategien, Risikomanagement und Setups.",
    min_rank: "aspiring",
    icon: "TR",
    member_count: 33,
  },
  {
    slug: "memecoin-trading",
    name: "Memecoin Trading",
    category: "Memecoin Trading",
    description: "High-Risk Research, Onchain-Tools, Narratives und Risikohinweise.",
    min_rank: "aspiring",
    icon: "M",
    member_count: 29,
  },
  {
    slug: "youtube-automation",
    name: "YouTube Automation",
    category: "YouTube Automation",
    description: "Automatisierte YouTube-Kanäle, Skripte, Thumbnails, Produktion, Teams und Monetarisierung.",
    min_rank: "aspiring",
    icon: "Y",
    member_count: 42,
  },
  {
    slug: "digital-business",
    name: "Digital Business",
    category: "Digital Business",
    description: "SaaS, Agenturen, Infoprodukte, Automationen und digitale Services.",
    min_rank: "builder",
    icon: "DB",
    member_count: 46,
  },
  {
    slug: "founder-pro",
    name: "Founder Pro Lounge",
    category: "Founder Pro",
    description: "Premium-Channel für exklusive Ressourcen, frühe Event-Zugänge und Pro-Diskussionen.",
    min_rank: "starter",
    requires_founder_pro: true,
    icon: "P",
    member_count: 24,
  },
];

export const groupPageContent = {
  reselling: {
    image_url: "https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1600&q=80",
    headline: "Reselling: Produkte finden, Margen sichern, operativ skalieren.",
    description: "Reselling bedeutet, profitable Produkte einzukaufen und über Marktplätze, Shops oder spezialisierte Kanäle weiterzuverkaufen. In dieser Gruppe geht es um Sourcing, Kalkulation, Marktplatz-Strategien und saubere Prozesse.",
    active_chats: 38,
    events_this_week: 2,
  },
  dropshipping: {
    image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1600&q=80",
    headline: "Dropshipping: Angebote testen, Creatives bauen, Shops optimieren.",
    description: "Dropshipping fokussiert sich auf schnelle Produkttests ohne eigenes Lager. Die Gruppe bündelt Austausch zu Lieferanten, Store-Aufbau, Ads, Creatives und Conversion-Optimierung.",
    active_chats: 31,
    events_this_week: 1,
  },
  "e-commerce": {
    image_url: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=1600&q=80",
    headline: "E-Commerce: Von ersten Bestellungen zu belastbaren Systemen.",
    description: "Hier treffen sich Shop-Betreiber, DTC-Brands und Online-Händler. Themen sind Conversion, Logistik, Retention, Performance Marketing, Sortiment und operative Skalierung.",
    active_chats: 44,
    events_this_week: 3,
  },
  "tiktok-creator": {
    image_url: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=1600&q=80",
    headline: "TikTok Creator: Reichweite, Funnels und Social Commerce.",
    description: "Diese Gruppe ist für Creator, Brands und Unternehmer, die TikTok als Wachstumskanal nutzen. Im Fokus stehen Hooks, Content-Systeme, Live Shopping, Creator Ads und Monetarisierung.",
    active_chats: 57,
    events_this_week: 2,
  },
  "ki-creator": {
    image_url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1600&q=80",
    headline: "KI Creator: Automatisierung, Content und neue Geschäftsmodelle.",
    description: "KI Creator bauen Workflows, Tools und Content-Systeme mit künstlicher Intelligenz. Die Gruppe hilft bei Automationen, Prompt-Systemen, Tool-Stacks und produktisierten Services.",
    active_chats: 29,
    events_this_week: 1,
  },
  trading: {
    image_url: "https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=1600&q=80",
    headline: "Trading: Prozesse, Risiko und disziplinierte Setups.",
    description: "Die Trading-Gruppe dient dem Austausch über Strategien, Journaling, Risiko-Management und Marktstruktur. Inhalte sind keine Finanzberatung und ersetzen keine eigene Recherche.",
    disclaimer: "Disclaimer: Alle Inhalte dienen nur dem Austausch und sind keine Anlageberatung, Kaufempfehlung oder Finanzberatung.",
    active_chats: 26,
    events_this_week: 1,
  },
  "memecoin-trading": {
    image_url: "https://images.unsplash.com/photo-1621504450181-5d356f61d307?w=1600&q=80",
    headline: "Memecoin Trading: Onchain Research mit maximalem Risikobewusstsein.",
    description: "Diese Gruppe behandelt Narratives, Onchain-Tools, Wallet-Tracking und Risiko-Regeln im Memecoin-Markt. Der Bereich ist hochspekulativ und nur für bewusstes Risikomanagement gedacht.",
    disclaimer: "Disclaimer: Memecoins sind extrem riskant. Inhalte sind keine Anlageberatung und können Totalverluste nicht ausschließen.",
    active_chats: 22,
    events_this_week: 1,
  },
  "youtube-automation": {
    image_url: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1600&q=80",
    headline: "YouTube Automation: Kanäle systematisch aufbauen und Produktion skalieren.",
    description: "Diese Gruppe bündelt Founder rund um automatisierte YouTube-Kanäle: Nischenrecherche, Skripte, Thumbnails, Produktionsteams, Monetarisierung und Qualitätskontrolle.",
    active_chats: 34,
    events_this_week: 2,
  },
  "digital-business": {
    image_url: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=1600&q=80",
    headline: "Digital Business: SaaS, Agenturen, Infoprodukte und Automationen.",
    description: "Digital Business bündelt Gründer mit digitalen Geschäftsmodellen. Im Fokus stehen Angebote, Vertrieb, Delivery, Automationen, Produktisierung und wiederkehrende Umsätze.",
    active_chats: 41,
    events_this_week: 2,
  },
};

export const groupMentors = [
  {
    id: "mentor-reselling",
    group_slugs: ["reselling"],
    name: "Leon Hartmann",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80",
    expertise: "Reselling Sourcing",
    tags: ["Sourcing", "Marktplätze", "Marge"],
    rating: 4.9,
    reviews: ["Sehr konkrete Einkaufssysteme.", "Hat meine Kalkulation direkt verbessert."],
    hourly_rate: "129 EUR / Monat · 4 Sessions",
    hourly_rate_cents: 12900,
    monthly_rate_cents: 12900,
    sessions_per_month: 4,
    bio: "Leon baut seit Jahren Reselling-Systeme mit Fokus auf saubere Margen, Prozesse und Lieferantenbeziehungen.",
    experience: "8 Jahre Reselling, mehrere 7-stellige Handelsumsätze, Fokus auf operative Skalierung.",
  },
  {
    id: "mentor-dropshipping",
    group_slugs: ["dropshipping", "e-commerce"],
    name: "Mira Schulte",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&q=80",
    expertise: "Shop Testing & Creatives",
    tags: ["Dropshipping", "Creatives", "Shop Testing"],
    rating: 4.8,
    reviews: ["Sehr guter Blick für Creatives.", "Klare Testpläne statt Bauchgefühl."],
    hourly_rate: "149 EUR / Monat · 4 Sessions",
    hourly_rate_cents: 14900,
    monthly_rate_cents: 14900,
    sessions_per_month: 4,
    bio: "Mira hilft bei Offer-Testing, Landing Pages und Creative-Systemen für Dropshipping und E-Commerce.",
    experience: "6 Jahre Performance Marketing, über 120 getestete Shop-Konzepte.",
  },
  {
    id: "mentor-ecommerce",
    group_slugs: ["e-commerce", "digital-business"],
    name: "Sarah Keller",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80",
    expertise: "E-Commerce Skalierung",
    tags: ["DTC", "Conversion", "Operations"],
    rating: 5.0,
    reviews: ["Extrem strukturiert.", "Sehr wertvoll für DTC-Skalierung."],
    hourly_rate: "199 EUR / Monat · 6 Sessions",
    hourly_rate_cents: 19900,
    monthly_rate_cents: 19900,
    sessions_per_month: 6,
    bio: "Sarah begleitet E-Commerce Brands von ersten Umsätzen zu belastbaren Prozessen und profitabler Skalierung.",
    experience: "DTC Growth Advisorin, ehemalige COO einer 8-stelligen Commerce Brand.",
  },
  {
    id: "mentor-tiktok",
    group_slugs: ["tiktok-creator", "ki-creator", "youtube-automation"],
    name: "Murat Aydin",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80",
    expertise: "Creator Funnels",
    tags: ["TikTok", "Creator", "Funnels"],
    rating: 4.7,
    reviews: ["Top Hooks und sehr praxisnah.", "Hat unseren Creator Funnel neu sortiert."],
    hourly_rate: "119 EUR / Monat · 3 Sessions",
    hourly_rate_cents: 11900,
    monthly_rate_cents: 11900,
    sessions_per_month: 3,
    bio: "Murat verbindet Creator Content, TikTok Ads und einfache Funnel-Mechaniken für digitale Produkte.",
    experience: "Creator Commerce, TikTok Ads und Content-Systeme für Creator Brands.",
  },
  {
    id: "mentor-trading",
    group_slugs: ["trading", "memecoin-trading"],
    name: "Daniel Voss",
    avatar_url: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&q=80",
    expertise: "Risk Management",
    tags: ["Trading", "Risk", "Journal"],
    rating: 4.6,
    reviews: ["Sehr klare Risiko-Regeln.", "Hilft beim Disziplin-Aufbau."],
    hourly_rate: "179 EUR / Monat · 4 Sessions",
    hourly_rate_cents: 17900,
    monthly_rate_cents: 17900,
    sessions_per_month: 4,
    bio: "Daniel fokussiert sich auf Risikomanagement, Journaling und systematische Trading-Prozesse.",
    experience: "10 Jahre Trading, Schwerpunkt Risiko, Psychologie und Prozessdisziplin.",
  },
];

export const groupResources = [
  {
    id: "discord-reselling",
    group_slug: "reselling",
    title: "Reselling Discord Deutschland",
    description: "Aktive Discord-Gruppe für Sourcing, Deals und Marktplatz-News.",
    category: "Discord-Gruppen",
    external_url: "https://example.com",
    status: "approved",
  },
  {
    id: "telegram-dropshipping",
    group_slug: "dropshipping",
    title: "Dropshipping Alerts",
    description: "Telegram-Kanal mit Creatives, Store-Beispielen und Lieferanten-Hinweisen.",
    category: "Telegram-Kanäle",
    external_url: "https://example.com",
    status: "approved",
  },
  {
    id: "youtube-tiktok",
    group_slug: "tiktok-creator",
    title: "TikTok Growth Kanal",
    description: "YouTube-Kanal zu Hooks, Creator Ads und organischem Wachstum.",
    category: "YouTube-Kanäle",
    external_url: "https://example.com",
    status: "approved",
  },
  {
    id: "course-ai",
    group_slug: "ki-creator",
    title: "KI Content Systeme",
    description: "Kurs zu KI-gestützter Content-Produktion und Automationen.",
    category: "Kurse",
    external_url: "https://example.com",
    status: "approved",
  },
  {
    id: "tool-digital",
    group_slug: "digital-business",
    title: "Automation Stack",
    description: "Tool-Liste für CRM, Automationen, Zahlungen und Reporting.",
    category: "Tools",
    external_url: "https://example.com",
    status: "approved",
  },
];

export const externalGroups = [
  {
    id: "ext-reselling-discord",
    group_slug: "reselling",
    name: "Top Deutsche Reselling Discord Server",
    description: "Deal-Alerts, Sourcing-Tipps und Marktplatz-Austausch für deutsche Reseller.",
    category: "Discord",
    member_count: 12800,
    average_rating: 4.8,
    external_url: "https://example.com/reselling-discord",
    status: "approved",
  },
  {
    id: "ext-reselling-sneaker",
    group_slug: "reselling",
    name: "Sneaker Cookgroup DACH",
    description: "Sneaker Releases, Raffles, Restocks und Bot-freie Reselling-Strategien.",
    category: "Discord",
    member_count: 7200,
    average_rating: 4.6,
    external_url: "https://example.com/sneaker",
    status: "approved",
  },
  {
    id: "ext-reselling-cardboard",
    group_slug: "reselling",
    name: "Cardboard Communities",
    description: "TCG, Sammelkarten, Grading und langfristige Inventory-Strategien.",
    category: "Telegram",
    member_count: 3400,
    average_rating: 4.4,
    external_url: "https://example.com/cardboard",
    status: "approved",
  },
  {
    id: "ext-dropshipping-ads",
    group_slug: "dropshipping",
    name: "Dropshipping Creative Lab",
    description: "Creatives, Winning Products, Supplier-Hinweise und Testing-Routinen.",
    category: "Discord",
    member_count: 9100,
    average_rating: 4.5,
    external_url: "https://example.com/dropshipping",
    status: "approved",
  },
  {
    id: "ext-ecommerce-dtc",
    group_slug: "e-commerce",
    name: "DTC Operators Germany",
    description: "Retention, Shopsysteme, Logistik und Conversion-Austausch.",
    category: "WhatsApp",
    member_count: 2800,
    average_rating: 4.7,
    external_url: "https://example.com/dtc",
    status: "approved",
  },
  {
    id: "ext-tiktok-hooks",
    group_slug: "tiktok-creator",
    name: "TikTok Hooks & Growth",
    description: "Hook-Analysen, Viral-Formate und Creator-Funnel für Social Commerce.",
    category: "Telegram",
    member_count: 15400,
    average_rating: 4.6,
    external_url: "https://example.com/tiktok",
    status: "approved",
  },
  {
    id: "ext-ai-creator",
    group_slug: "ki-creator",
    name: "AI Creator Automation",
    description: "KI-Workflows, Content-Automation, Tool-Stacks und Prompt-Systeme.",
    category: "Discord",
    member_count: 6400,
    average_rating: 4.3,
    external_url: "https://example.com/ai-creator",
    status: "approved",
  },
  {
    id: "ext-trading-risk",
    group_slug: "trading",
    name: "Risk First Trading",
    description: "Journal, Risikoregeln und Marktstruktur ohne Anlageberatung.",
    category: "Discord",
    member_count: 5100,
    average_rating: 4.2,
    external_url: "https://example.com/trading",
    status: "approved",
  },
  {
    id: "ext-memecoin-onchain",
    group_slug: "memecoin-trading",
    name: "Onchain Research DACH",
    description: "Wallet-Tracking, Narratives und High-Risk Research für Memecoins.",
    category: "Telegram",
    member_count: 8900,
    average_rating: 4.1,
    external_url: "https://example.com/onchain",
    status: "approved",
  },
  {
    id: "ext-youtube-creators",
    group_slug: "youtube-automation",
    name: "YouTube Automation Ressourcen",
    description: "Skripte, Thumbnails, Nischenrecherche, Produktionsteams und Monetarisierungsstrategien.",
    category: "Discord",
    member_count: 7600,
    average_rating: 4.5,
    external_url: "https://example.com/youtube",
    status: "approved",
  },
  {
    id: "ext-digital-saas",
    group_slug: "digital-business",
    name: "Digital Business Builders",
    description: "SaaS, Agenturen, Infoprodukte und Automationen für digitale Geschäftsmodelle.",
    category: "WhatsApp",
    member_count: 4200,
    average_rating: 4.7,
    external_url: "https://example.com/digital-business",
    status: "approved",
  },
];

export const groupEvents = [
  {
    id: "event-reselling",
    group_slugs: ["reselling"],
    title: "Reselling Sourcing Night",
    starts_at: "2026-06-07T18:00:00.000Z",
    price_cents: 4900,
    min_rank: "aspiring",
  },
  {
    id: "event-commerce",
    group_slugs: ["dropshipping", "e-commerce"],
    title: "E-Commerce Scaling Workshop",
    starts_at: "2026-06-15T10:00:00.000Z",
    price_cents: 14900,
    min_rank: "starter",
  },
  {
    id: "event-creator",
    group_slugs: ["tiktok-creator", "ki-creator", "youtube-automation"],
    title: "Creator Monetization Call",
    starts_at: "2026-06-20T17:00:00.000Z",
    price_cents: 0,
    min_rank: "aspiring",
  },
  {
    id: "event-trading",
    group_slugs: ["trading", "memecoin-trading"],
    title: "Risk First Trading Session",
    starts_at: "2026-06-24T19:00:00.000Z",
    price_cents: 9900,
    min_rank: "starter",
  },
];

export const groupTemplates = [
  {
    id: "template-margin",
    group_slug: "reselling",
    title: "Marge-Rechner",
    file_type: "Excel",
    price_cents: 1900,
  },
  {
    id: "template-supplier",
    group_slug: "dropshipping",
    title: "Supplier Outreach Vorlage",
    file_type: "PDF",
    price_cents: 2900,
  },
  {
    id: "template-content",
    group_slug: "tiktok-creator",
    title: "30 Tage Content Plan",
    file_type: "Excel",
    price_cents: 1900,
  },
  {
    id: "template-risk",
    group_slug: "trading",
    title: "Risk Journal",
    file_type: "Excel",
    price_cents: 3900,
  },
  {
    id: "template-ops",
    group_slug: "digital-business",
    title: "Business KPI Dashboard",
    file_type: "Excel",
    price_cents: 4900,
  },
  {
    id: "template-shop-testing",
    group_slug: "e-commerce",
    title: "Shop Audit Checkliste",
    file_type: "PDF",
    price_cents: 2900,
  },
  {
    id: "template-ai-workflows",
    group_slug: "ki-creator",
    title: "KI Workflow Library",
    file_type: "PDF",
    price_cents: 3900,
  },
  {
    id: "template-memecoin-risk",
    group_slug: "memecoin-trading",
    title: "Onchain Risk Sheet",
    file_type: "Excel",
    price_cents: 4900,
  },
  {
    id: "template-youtube-scripts",
    group_slug: "youtube-automation",
    title: "YouTube Automation Script Vorlagen",
    file_type: "PDF",
    price_cents: 2900,
  },
];

export const sampleEvents = [
  {
    id: "networking-dinner",
    slug: "networking-dinner",
    title: "Networking Dinner",
    description: "Kuratierter Abend mit verifizierten Gründern, Investoren und operativen Unternehmern.",
    starts_at: "2026-06-04T18:00:00.000Z",
    price_cents: 4900,
    min_rank: "builder",
    location_text: "Berlin",
    category: "Networking",
    image_url: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200&q=80",
    capacity: 50,
    booked_spots: 27,
    group_slugs: [],
    group_label: "Für alle Founder",
    long_description:
      "Ein kuratierter Abend für verifizierte Gründer, Investoren und operative Unternehmer. Im Mittelpunkt stehen echte Gespräche, konkrete Erfahrungen und neue Kontakte, die über oberflächliches Networking hinausgehen.",
    speakers: [
      {
        name: "Sarah Keller",
        bio: "DTC Growth Advisorin und ehemalige COO einer achtstelligen Commerce Brand.",
        image_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&q=80",
      },
      {
        name: "Jonas Weber",
        bio: "Finance- und Operations-Berater für wachsende Gründerteams.",
        image_url: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500&q=80",
      },
    ],
    agenda: ["19:00 Begrüßung", "19:30 Dinner & Networking", "21:00 Founder Roundtable", "22:00 Open Networking"],
  },
  {
    id: "builder-workshop",
    slug: "builder-workshop",
    title: "Builder Workshop",
    description: "Taktischer Workshop zu Wachstum, Prozessen, BWA und Teamaufbau.",
    starts_at: "2026-06-13T10:00:00.000Z",
    price_cents: 14900,
    min_rank: "builder",
    location_text: "Hamburg",
    category: "Workshop",
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&q=80",
    capacity: 35,
    booked_spots: 18,
    group_slugs: ["dropshipping", "e-commerce", "digital-business"],
    group_label: "Für E-Commerce, Dropshipping und Digital Business",
    long_description:
      "Ein taktischer Tagesworkshop für Unternehmer, die Wachstum, Prozesse und Zahlen besser verbinden wollen. Du arbeitest an konkreten Hebeln für Team, BWA, Delivery und wiederholbares Wachstum.",
    speakers: [
      {
        name: "Mira Schulte",
        bio: "Performance-Marketing-Expertin mit Fokus auf Offer-Testing und Creative-Systeme.",
        image_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&q=80",
      },
      {
        name: "Jonas Weber",
        bio: "Berät Gründer bei Finanzsteuerung, BWA, Planung und operativen Prozessen.",
        image_url: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500&q=80",
      },
    ],
    agenda: ["10:00 Strategie", "12:00 Prozessdesign", "14:00 Finanz-Review", "15:30 Umsetzung", "17:00 Q&A"],
  },
  {
    id: "founder-conference",
    slug: "founder-conference",
    title: "Founder Jahreskonferenz",
    description: "Konferenz für Gründer, Creator und Unternehmer mit Talks, Panels und Deal-Making.",
    starts_at: "2026-06-21T19:00:00.000Z",
    price_cents: 19900,
    min_rank: "aspiring",
    location_text: "München",
    category: "Konferenz",
    image_url: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=1200&q=80",
    capacity: 250,
    booked_spots: 142,
    group_slugs: [],
    group_label: "Für alle Communities",
    long_description:
      "Die große Founder Jahreskonferenz bringt Gründer, Creator und Unternehmer aus allen Branchen zusammen. Talks, Panels, Breakouts und Deal-Making schaffen einen kompakten Tag voller Substanz.",
    speakers: [
      {
        name: "Murat Aydin",
        bio: "Creator-Commerce-Operator mit Fokus auf TikTok, Funnels und Social Commerce.",
        image_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&q=80",
      },
      {
        name: "Leon Hartmann",
        bio: "Reselling-Unternehmer mit mehreren siebenstelligen Handelsumsätzen.",
        image_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&q=80",
      },
      {
        name: "Sarah Keller",
        bio: "DTC Growth Advisorin für Commerce Brands und skalierende Teams.",
        image_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&q=80",
      },
    ],
    agenda: ["09:30 Opening", "11:00 Wachstumspanels", "14:00 Breakouts", "17:00 Networking", "19:00 After Event"],
  },
];

export const partnerResources = [
  {
    id: "reselling-tools",
    name: "ResellOS",
    description: "Tool-Stack für Produktrecherche, Kalkulation und Reselling-Workflows.",
    category: "Reselling",
    external_url: "https://example.com",
  },
  {
    id: "dropshipping-supplier",
    name: "Supplier Hub",
    description: "Kuratierte Lieferanten und Fulfillment-Partner für Dropshipping-Brands.",
    category: "Dropshipping",
    external_url: "https://example.com",
  },
  {
    id: "tiktok-analytics",
    name: "Creator Metrics",
    description: "Analytics und Content-Tracking für TikTok Creator und Social Commerce.",
    category: "TikTok",
    external_url: "https://example.com",
  },
  {
    id: "ecommerce-stack",
    name: "Commerce Suite",
    description: "Rabatte auf Shop-Apps, Checkout-Optimierung und E-Commerce Operations.",
    category: "E-Commerce",
    external_url: "https://example.com",
  },
];
