/** Demo-Transaktionen für Gäste (nicht eingeloggt). */
export const GUEST_DEMO_TRANSACTIONS = [
  {
    id: "guest-demo-1",
    vendor: "Amazon",
    date: "18.04.2026",
    category: "Demo",
    amount: 129.9,
    currency: "EUR",
    receiptFound: true,
    vatReceiptMissing: false,
    supportEmail: "rechnung@amazon.de",
    isProFeature: false,
    aiStatus: "",
  },
  {
    id: "guest-demo-2",
    vendor: "Adobe",
    date: "16.03.2026",
    category: "Demo",
    amount: 59.49,
    currency: "EUR",
    receiptFound: false,
    vatReceiptMissing: true,
    supportEmail: "support@adobe.com",
    isProFeature: false,
    aiStatus: "",
  },
  {
    id: "guest-demo-3",
    vendor: "Slack",
    date: "09.03.2026",
    category: "Demo",
    amount: 22.4,
    currency: "EUR",
    receiptFound: false,
    vatReceiptMissing: true,
    supportEmail: "feedback@slack.com",
    isProFeature: false,
    aiStatus: "",
  },
];

/** Demo-Fallback für den Gmail Live-Scan, wenn die Gmail API im Review noch blockiert. */
export const GMAIL_SCAN_DEMO_TRANSACTIONS = [
  {
    id: "gmail-demo-adobe",
    vendor: "Adobe",
    date: "22.04.2026",
    category: "Software",
    amount: 59.49,
    currency: "EUR",
    receiptFound: true,
    vatReceiptMissing: false,
    supportEmail: "support@adobe.com",
    isProFeature: true,
    aiStatus: "demo_fallback",
  },
  {
    id: "gmail-demo-amazon",
    vendor: "Amazon Business",
    date: "21.04.2026",
    category: "Bürobedarf",
    amount: 129.9,
    currency: "EUR",
    receiptFound: true,
    vatReceiptMissing: false,
    supportEmail: "rechnung@amazon.de",
    isProFeature: true,
    aiStatus: "demo_fallback",
  },
  {
    id: "gmail-demo-google-cloud",
    vendor: "Google Cloud",
    date: "19.04.2026",
    category: "Cloud Services",
    amount: 284.15,
    currency: "EUR",
    receiptFound: true,
    vatReceiptMissing: false,
    supportEmail: "cloud-support@google.com",
    isProFeature: true,
    aiStatus: "demo_fallback",
  },
  {
    id: "gmail-demo-slack",
    vendor: "Slack",
    date: "17.04.2026",
    category: "Kommunikation",
    amount: 42.8,
    currency: "EUR",
    receiptFound: false,
    vatReceiptMissing: true,
    supportEmail: "feedback@slack.com",
    isProFeature: true,
    aiStatus: "demo_fallback",
  },
  {
    id: "gmail-demo-notion",
    vendor: "Notion",
    date: "15.04.2026",
    category: "Produktivität",
    amount: 18,
    currency: "EUR",
    receiptFound: true,
    vatReceiptMissing: false,
    supportEmail: "team@makenotion.com",
    isProFeature: true,
    aiStatus: "demo_fallback",
  },
];
