import JSZip from "jszip";
import { jsPDF } from "jspdf";
import { supabase } from "../lib/supabaseClient";

function parseGermanDate(dateString) {
  const raw = String(dateString ?? "").trim();
  if (!raw) return new Date(NaN);
  const parts = raw.split(".");
  if (parts.length === 3) {
    const [day, month, year] = parts.map((p) => Number(p));
    if (Number.isFinite(day) && Number.isFinite(month) && Number.isFinite(year)) {
      return new Date(year, month - 1, day);
    }
  }
  const parsed = Date.parse(raw);
  return Number.isFinite(parsed) ? new Date(parsed) : new Date(NaN);
}

function toMonthKey(dateString) {
  const date = parseGermanDate(dateString);
  if (Number.isNaN(date.getTime())) return "unknown";
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
}

function toIsoDate(dateString) {
  const date = parseGermanDate(dateString);
  if (Number.isNaN(date.getTime())) return "unknown-date";
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
}

function sanitizeVendor(vendor) {
  return String(vendor ?? "Unknown")
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, "_")
    .trim();
}

function formatEuroToken(amount) {
  const value = Number(amount ?? 0).toFixed(2).replace(".", ",");
  return `${value}_Euro`;
}

function buildFilename(transaction) {
  return `${toIsoDate(transaction.date)}_${sanitizeVendor(transaction.vendor)}_${formatEuroToken(transaction.amount)}.pdf`;
}

function buildSummaryPdf(rows, language, monthKey) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const title = language === "en" ? `Monthly export ${monthKey}` : `Monatsexport ${monthKey}`;
  const amountFormatter = new Intl.NumberFormat(language === "en" ? "en-US" : "de-DE", {
    style: "currency",
    currency: "EUR",
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(title, 16, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(language === "en" ? "Generated by Receipto" : "Erstellt mit Receipto", 16, 24);

  let y = 32;
  rows.forEach((row, index) => {
    const line = `${index + 1}. ${row.date} | ${row.vendor} | ${row.category} | ${amountFormatter.format(Number(row.amount ?? 0))} | ${
      row.receiptFound ? (language === "en" ? "Receipt found" : "Beleg vorhanden") : (language === "en" ? "Missing" : "Fehlend")
    }`;
    const wrapped = doc.splitTextToSize(line, 178);
    if (y + wrapped.length * 5 > 285) {
      doc.addPage();
      y = 18;
    }
    doc.text(wrapped, 16, y);
    y += wrapped.length * 5 + 2;
  });

  return doc.output("arraybuffer");
}

function buildInternalReceiptPdf(transaction, language) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const title = language === "en" ? "Internal receipt / Substitute document" : "Eigenbeleg / Ersatzbeleg";
  const amount = Number(transaction.amount ?? 0).toFixed(2);
  const left = 18;
  let y = 22;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(title, left, y);
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const lines = [
    `${language === "en" ? "Date" : "Datum"}: ${transaction.date ?? "-"}`,
    `${language === "en" ? "Vendor" : "Zahlungsempfaenger"}: ${transaction.vendor ?? "-"}`,
    `${language === "en" ? "Purpose" : "Verwendungszweck"}: ${transaction.category ?? "General"}`,
    `${language === "en" ? "Gross amount" : "Bruttobetrag"}: ${amount} ${transaction.currency ?? "EUR"}`,
    language === "en"
      ? "Reason: Original receipt is not available."
      : "Begruendung: Der Originalbeleg ist nicht auffindbar.",
  ];
  lines.forEach((line) => {
    const wrapped = doc.splitTextToSize(line, 175);
    doc.text(wrapped, left, y);
    y += wrapped.length * 6;
  });

  return doc.output("arraybuffer");
}

function buildMissingStoragePlaceholderPdf(transaction, language) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(language === "en" ? "Receipt placeholder" : "Beleg-Platzhalter", 18, 22);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const lines = [
    `${language === "en" ? "Date" : "Datum"}: ${transaction.date ?? "-"}`,
    `${language === "en" ? "Vendor" : "Anbieter"}: ${transaction.vendor ?? "-"}`,
    `${language === "en" ? "Amount" : "Betrag"}: ${Number(transaction.amount ?? 0).toFixed(2)} ${transaction.currency ?? "EUR"}`,
    language === "en"
      ? "Original receipt marked as found, but no storage file was resolved."
      : "Originalbeleg ist als vorhanden markiert, aber keine Datei im Storage wurde gefunden.",
  ];
  let y = 34;
  lines.forEach((line) => {
    const wrapped = doc.splitTextToSize(line, 175);
    doc.text(wrapped, 18, y);
    y += wrapped.length * 6;
  });
  return doc.output("arraybuffer");
}

async function tryDownloadFromStorage(transaction) {
  const pathCandidate =
    transaction.receiptPath ?? transaction.receipt_path ?? transaction.storagePath ?? transaction.filePath ?? null;
  if (!pathCandidate) return null;

  const buckets = [transaction.receiptBucket, "receipts", "invoices", "invoice-receipts"].filter(Boolean);
  for (const bucket of buckets) {
    const { data, error } = await supabase.storage.from(bucket).download(pathCandidate);
    if (!error && data) {
      return data;
    }
  }
  return null;
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export async function exportMonthZip({ transactions, selectedMonth, language }) {
  const monthRows = (transactions ?? []).filter((row) => toMonthKey(row.date) === selectedMonth);
  if (monthRows.length === 0) return { exportedCount: 0 };

  const zip = new JSZip();
  zip.file("Zusammenfassung.pdf", buildSummaryPdf(monthRows, language, selectedMonth));

  for (const row of monthRows) {
    const filename = buildFilename(row);
    if (row.receiptFound) {
      const existing = await tryDownloadFromStorage(row);
      if (existing) {
        zip.file(filename, existing);
      } else {
        zip.file(filename, buildMissingStoragePlaceholderPdf(row, language));
      }
    } else {
      zip.file(filename, buildInternalReceiptPdf(row, language));
    }
  }

  const zipBlob = await zip.generateAsync({ type: "blob" });
  triggerDownload(zipBlob, `${selectedMonth}_Monatsexport.zip`);
  return { exportedCount: monthRows.length };
}

